<div id="container">
    <div id="ask-id">
        <form method="post" id="form-id" action="https://camille-marro.alwaysdata.net/personnage">
            <input type="text" name="id-personnage" id="id-personnage" placeholder="Entrer l'id du personnage">
            <button type="submit" id="ask-id-button">Chercher</button>
        </form>
    </div>
    <div id="error_field"><?php if(isset($_GET['error'])) echo $_GET['error'];?></div>
    <div id="infos-container">
        <div id="summary-container">
            <div id="title">Les chroniques d'Akira</div>
            <div id="summary">
                <h3>Chapitre 1</h3>
                Après la rencontre avec Ayas Baltris, rencontre avec le chef de la ville qui se prénomme Frairr. Il donne la mission suivante au groupe : amener à un certain Salqred, un petit coffret. Le groupe ne devra en aucun cas regarder ce que contient le coffret. Si Salqred découvre que le coffret a été ouvert, il a ordre de couper la tête à tous les membres du groupe.  La mission donnée, le groupe a une semaine pour partir en mission. Une fois tous les achats effectués pour le départ en mission comme notamment des plantes, de l’équipement de survie, de la nourriture et des cordes. Le groupe se retrouve à l’auberge du Lion Heureux pour y passer la nuit.<br>
                Au petit matin, prêt à partir, ils se dirigent vers le Nord direction Molbern, pour atteindre la ville ils vont devoir traverser la forêt du Borzon. Après une petite demi-journée de marche, le seul pont permettant de traverser la rivière du Borzon est brisé, ils doivent donc trouver une solution pour passer. Momiji traverse le pont avec l’aide d’Idas et explore un peu les lieux qui suivent le pont, il découvre une petite grotte et tue un lapin qu’il avait aperçu dans un buisson. Pendant ce temps Jin s’encorde et avec l’aide de Cheezy Gnocki et d’Idas il descend en rappel pour s’approcher de la rivière. <br>
                Lorsqu’il trempe le pied, il est emporté par le courant. Gêné par Idas Cheezy Gnocki a du mal à le rattraper. Idas lâche alors la corde et décide de créer un contre courant pour aider Cheezy Gnocki, qui, grâce à sa force arrive à remonter Jin. Jin continue sa session d’escalade et observe un peu le lit de rivière et remarque une charrette brisée retenue par un rocher dans le courant qui a emporté toutes les marchandises. Cheezy Gnocki l’aide à remonter.<br>
                Après un peu d'exploration, le groupe décide d’utiliser un tronc d’arbre pour faire office de pont. Pour transporter le tronc, Idas utilise sa magie pendant que Jin le guide pour poser le tronc juste à côté du pont brisé. Une fois le tronc posé Momiji demande à ses compagnons de venir l’aider à transporter un autre tronc qui est de son côté. Idas refait alors le même sort et dépose le tronc à côté de l’autre. Une fois les deux troncs posés Jin coupe la corde en 3 et attache les troncs en eux pour plus de solidité.<br>
                Il faut maintenant faire traverser les chevaux ainsi que la charrette remplie. Jin calme les chevaux d’une main de maître et commence à les faire monter sur les troncs, pendant ce temps Gnocki soulève d’une seule main la charrette pour l’aider à monter les troncs et le groupe passe enfin le pont après une bonne demi journée.<br>
                <h3>Chapitre 5</h3>
                Une fois devant Molbern, Salqred attend le groupe avec des informations importantes tout d’abord le groupe accepte de continuer l’aventure. Ils apprennent qu’un groupe de voleurs de qui se font appeler les sourires du corbeau sont à l’origine du vole du coffret. Ils seraient apparemment dans le Deaman. Avant de partir dans ce grand désert Salqred leur propose de se préparer et d’aller voir Frairr à Koly pour obtenir des sous en avance pour leur voyage.<br>
                Après des découvertes sur la magie et les élémentaires à la bibliothèque de Molbern, le groupe se met en route pour Koly. Une fois à Koly, le rendez-vous avec Frairr est vite pris, Salqred explique ce qui c’est passé et où ils vont. Frairr accepte et explique plus en détail le contenu du petit coffret. Il renfermait le cristal de défense physique, un cristal qui permet au porteur de se protéger contre n’importe quelle attaque physique et il explique au groupe l’histoire autour des six cristaux légendaires d’Akira.<br>
                Le groupe après de nombreuses négociations arrive à obtenir une bourse de 215 pièces d’or pour le voyage. Une fois les préparatifs très rapidement terminés, il est temps de partir pour le Deaman. Sur la route les aventuriers croise Nelisk, la célèbre panthère noir aux yeux d’émeraudes. Grâce à leur nouvelle connaissance des bêtes fantastiques, ils savent qu’elle attend quelque chose d’eux. Ils font alors un spectacle son et lumière pour impressionner la bête, qui satisfaite s’en va.<br>                        Ils tombent ensuite sur des ruines antiques, et dans un temps après avoir résolu une énigme, ils découvrent un engrenage avec un sigle étrange dessus.<br>
                <h3>Chapitre 6</h3>
                Une fois l’exploration des ruines terminée, le groupe se remet en route vers leur nouvelle destination Zralo, la ville qui a la réputation d’être le berceau des plus grands malfrats d’Akira. Sur leur route, les aventuriers croisent une étrange charrette qui avance toute seule. Un marchand ambulant se trouve au sommet et leur propose d’acheter ses objets enchantés. Le groupe se retrouve finalement en possession d’une tirelire cochon magique qui génère des pièces, d’un médiator taillé dans du bois magique et du 7 de trèfle du jeu de Dreqor. Une fois leur achat fait, le groupe continue sa route et fait une petite pause pour se reposer. Pause pendant laquelle Salqred s’empoisonne mais grâce aux aptitudes de Momiji il survivra.<br>
                Le lendemain le groupe arrive enfin à Zralo, village situé au bord du lac des larmes, lac très particulier car l’eau n’y fait aucun mouvement, elle semble figée dans le temps. Malgré des avertissements avérés d’une vieille dame qui se trouvera être la chaman du village, Roland touche du bout de ses doigts l’eau du lac et se retrouve maudit. Tout le mal qu’il inflige aux gens qui l’entoure lui sera aussi transmis. Pour enlever cette malédiction il lui faudra tuer un être humain “pur”, c'est-à-dire un être sans aucune volonté de nuire ou mauvaise pensée.<br>
                Le reste du groupe cependant essaie de regrouper des informations quant aux sourires du corbeau, le clan de voleur responsable du vol du cristal. Les différentes personnes interrogées semblent toutes méfiantes hormis le barman de l’auberge du cheval gris qui leur propose de revenir le soir afin de partager des informations. Une fois la discussion terminée, le groupe décide de prendre une chambre dans l’auberge et d’y passer la nuit.<br>
                <h3>Chapitre 7</h3>
                Une fois réveillé, le groupe est attendu par Aele, le chef de la ville qui leur explique, qu’un groupe d’assassins envoyé par les sourires du corbeau, est en route et sera là d’ici 2 à 3 jours. Il leur explique aussi qu’une vieille légende raconte l’histoire de la cité perdue des hommes lézards où se trouverait un objet capable de retirer les malédictions.<br>
                Le groupe décide de rester la journée à Zralo pour obtenir de nouvelles informations, Jin se rend d’abord dans la maison d’Aele pour lui demander plusieurs informations sur le chef du sourire des corbeaux. Il se rend ensuite avec C36P1 à la cabane des chasseurs où ils découvrent leur technique de chasse aux loups.<br>
                Pendant ce temps le reste du groupe fait des achats et passe la majeure partie de la journée à la taverne.<br>
                Jin et C36P1 décident d’aller voir la chaman pour obtenir des renseignements sur la malédiction de Roland. Méfiant de cette vieille femme, ils préfèrent la tester et C36P1 touche du bout de ce qui semble être ses doigts la surface du lac des larmes. La chaman leur apprend qu’il est maudit et qu’il sera moins agile qu’auparavant. Suite à cette révélation, ils essaient de convaincre la chaman de leur donner des informations sur les malédictions et sur ses recherches. Énervée, la chaman les fait sortir de force de sa tour et rejoignent leurs amis à la taverne.<br>
                Pendant cette aventure, Héra tente de séduire un homme seul qui boit à une table de la taverne. L’Homme la convainc de le suivre jusqu’à chez lui. Une fois devant sa maison, elle se rappelle qu’elle a sur elle l’ensemble de la fortune du groupe et décide de retourner très rapidement à la taverne pour y déposer l’argent et demander à Idas de la suivre discrètement au cas où ils se passeraient quelque chose de bizarre. Elle rejoint le point de rendez-vous mais l’homme a disparu et semble être parti.<br>
                Le soir, le groupe se retrouve à la taverne du cheval gris et Salqred leur explique qu’il partira au petit matin, qu'ils soient prêts ou non. Empli de folie et d’alcool, Jin se donne en spectacle pour se vanter de ses objets et brise la table de la taverne avant de s'effondrer de fatigue dessus. Ce petit geste lui coûtera toute sa bourse et tous ses objets. Une fois les festivités passées, les membres du groupe se couchent et la nuit se passe.<br>
            </div>
        </div>
        <div id="path-container">
            <div id="path-img">
                <img src="/public/assets/images/path.jpg" alt="map du monde">
            </div>
        </div>
    </div>
</div>